[user]
name = "Luke Frisken"
email = "l.frisken@gmail.com"

[git]
subprocess = true

[ui]
editor = "nvim"
merge-editor = "vscode"
# diff-formatter = ":git" # required by `delta`
diff-formatter = "delta"
pager=["delta", "--pager", "less -FRX"] # Keeps output from the terminal after closing the pager

[diff]
tool = "delta"

[merge-tools]
delta.diff-expected-exit-codes = [0, 1]

# These options allow for `jj diff` and `jj show` to clear the output from the terminal after closing the pager.
[[--scope]]
--when.commands = ["diff", "show"]
[--scope.ui]
pager = "delta"
diff-formatter = "delta"
